/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(): void;
export function __wbg_vector_free(a: number): void;
export function __wbg_get_vector_x(a: number): number;
export function __wbg_set_vector_x(a: number, b: number): void;
export function __wbg_get_vector_y(a: number): number;
export function __wbg_set_vector_y(a: number, b: number): void;
export function vector_new(a: number, b: number): number;
export function vector_add(a: number, b: number): number;
export function vector_subtract(a: number, b: number): number;
export function vector_scale_by(a: number, b: number): number;
export function vector_length(a: number): number;
export function vector_normalize(a: number): number;
export function vector_equal_to(a: number, b: number): number;
export function vector_is_opposite(a: number, b: number): number;
export function vector_dot_product(a: number, b: number): number;
export function __wbg_game_free(a: number): void;
export function __wbg_get_game_width(a: number): number;
export function __wbg_set_game_width(a: number, b: number): void;
export function __wbg_get_game_height(a: number): number;
export function __wbg_set_game_height(a: number, b: number): void;
export function __wbg_get_game_speed(a: number): number;
export function __wbg_set_game_speed(a: number, b: number): void;
export function __wbg_get_game_direction(a: number): number;
export function __wbg_set_game_direction(a: number, b: number): void;
export function __wbg_get_game_food(a: number): number;
export function __wbg_set_game_food(a: number, b: number): void;
export function __wbg_get_game_score(a: number): number;
export function __wbg_set_game_score(a: number, b: number): void;
export function game_new(a: number, b: number, c: number, d: number, e: number): number;
export function game_is_over(a: number): number;
export function game_process(a: number, b: number, c: number): void;
export function game_get_snake(a: number): number;
export function __wbindgen_exn_store(a: number): void;
